hi! link typescriptVariable Keyword
hi! link typescriptBinaryOp Keyword
hi! link typescriptAssign Keyword
hi! link typescriptBOMWindowMethod Function
hi! link typescriptBraces Comment
hi! link typescriptObjectLabel Property
hi! link typescriptArrowFunc Operator
hi! link tsxCloseString htmlTag
hi! link typescriptObjectColon Comment
hi! link typescriptOperator Operator
hi! link tsxTagName Keyword
